# content taken from https://blog.ouseful.info/2021/11/10/simple-jupytext-github-action-to-update-jupyter-ipynb-notebooks-from-markdown/
name: convert-jupyter-notebooks

on:
  workflow_run:
    workflows: ["tests"]
    branches:
      - main
    types:
      - completed

jobs:
  create-jupyter-notebooks:
    runs-on: ubuntu-latest

      # required by https://github.com/stefanzweifel/git-auto-commit-action
    permissions:
      # Give the default GITHUB_TOKEN write permission to commit and push the
      # added or changed files to the repository.
      contents: write

    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}

      - name: install deps
        run: |
          python -m venv venv
          source venv/bin/activate
          python -m pip install --extra-index-url https://download.pytorch.org/whl/cpu torch
          python -m pip install -r ./requirements.txt

      - name: convert
        run: |
          cd notebooks
          make -B

        # Auto commit any updated notebook files
      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          # This would be more useful if the git hash were referenced?
          commit_message: automated jupytext conversion of py:percent files to ipynb
          file_pattern: 'notebooks/*ipynb'
          status_options: '--ignored' #ipynb files are in the notebooks/.gitignore
          add_options: '--force'
